#pragma config(Sensor, dgtl1,  color,          sensorDigitalIn)
#pragma config(Sensor, dgtl2,  side,           sensorDigitalIn)
#pragma config(Sensor, dgtl3,  mogoEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  cbarEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, dgtl9)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           mogoLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           cbar,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mogoRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          backRight,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl11)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "ITZDriverv1.c"
#include "ITZauton.c"

bool joystick2 = false;

void pre_auton()
{
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}
task autonomous()
{
  auton(color, side);
}
task usercontrol()
{
  while (true){
  if (joystick2 == true){
  	//josh's joystick
		drive();
   	mogo(SensorValue[mogoEncoder]);
   	intake();
 		//anish's joystick
   	//lift (sep task)
   	//scoring (sep task)
   	//
   	//if editbutton is pressed
  	//if resetbutton is pressed
  }
  else{
  	int leftdrive = -vexRT[Ch3];
   	int rightdrive = vexRT[Ch2];
   	motor(backLeft) = leftdrive;
   	motor(frontLeft) = leftdrive;
   	motor(backRight) = rightdrive;
   	motor(frontRight) = rightdrive;
 	}
  }
}
